
// localhost
POST http://localhost:10000/contacts HTTP/1.1 content-type: application/json

{
    "firstName":"Jaden", "lastName":"Jensen", "email":"Jensen@fakemail.com", "favoriteColor":"Blue", "birthday":"05/18/1999"

}

GET http://localhost:10000/contacts

GET http://localhost:10000/contacts/6326567a07ec9687f1155195

GET http://localhost:10000/contacts/632656a007ec9687f1155196

GET http://localhost:10000/contacts/632656af07ec9687f1155197

GET http://localhost:10000/contacts/63265c7f07ec9687f1155198


// render

GET https://contactsite-nfh3.onrender.com/contacts

GET https://contactsite-nfh3.onrender.com/contacts/6326567a07ec9687f1155195

GET https://contactsite-nfh3.onrender.com/contacts/632656a007ec9687f1155196

GET https://contactsite-nfh3.onrender.com/contacts/632656af07ec9687f1155197

GET https://contactsite-nfh3.onrender.com/contacts/63265c7f07ec9687f1155198




